version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    # イメージ名を指定
    image: atcoder
    # localとcontainer間のファイルを同期させる
    # ${local}:${container}
    volumes:
      - ./problems:/root/problems:cached
      - ./library:/root/library:cached
      - ./.vscode:/root/.vscode:cached
    tty: true
