services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    # イメージ名を指定
    image: atcoder
    # localとcontainer間のファイルを同期させる
    # ${local}:${container}
    volumes:
      - ./problems:/root/problems:cached
      - ./library:/root/library:cached
      - ./.vscode:/root/.vscode:cached
      - ./templates:/root/.config/atcoder-cli-nodejs
      - ../note:/root/note:cached
    command: >
      acc config default-template py && tail -f /dev/null
    stdin_open: true
    tty: true
